package com.skeeterSoftworks.StockLocalServer.to.enums;

public enum ERole {
	ADMIN,
	OPERATOR,
	ADMIN_TECHNOLOGY,
	ADMIN_STOCK_INBOUND,
	ADMIN_STOCK_OUTBOUND,
	ADMIN_PRODUCTION,
	SALES_ADMIN,
	PURCHASING_ADMIN,
	PRODUCTION_PLANNING_ADMIN
}
